### PR TITLE
Fix overflow issues properly

### LINKED ISSUE #53: Search autosuggest not displayed
Caused by #52 trying to fix another overflow bug.

### PR DESCRIPTION
**Pull request by charypar**
... by moving the typeahead suggestions to a different place for V2

Fix #53

### CODE REVIEW

File: src/js/search.js [hunk 1]
```diff
@@ -72,11 +72,28 @@ module.exports = {
...
 		if (flags.get('typeahead')) {
-			new Typeahead(
-				header.querySelector('.js-search'),
+			var container, input;
+
+			if (flags.get('mastheadV2')) {
+				container = header.querySelector('.js-primary-row > div');
+				input = header.querySelector('.js-search input[type="search"]');
+			} else {
+			 	container = header.querySelector('.js-search');
```
Comment (ironsidevsquincy) [inline src/js/search.js]: some `js-` classes on the `div` and `input`?

**Comment by ironsidevsquincy** [comment]
:+1:
